-- Notification Icon

notify_icon_x = 13
notify_icon_y = 9999 -- 620

local original_set_notification = actor_menu.set_notification

function set_notification(typ, texture, tm, snd)
	original_set_notification(typ, texture, tm, snd)

	local hud = get_hud()
	if (hud) then
		cs = hud:GetCustomStatic("notify_icon")
		pos = cs:wnd():GetWndPos()
		pos.x = notify_icon_x
		pos.y = notify_icon_y
		cs:wnd():SetWndPos(pos)
	end
end

actor_menu.set_notification = set_notification
